"""Add group chats and avatars

Revision ID: ad2aec42bc51
Revises: 835dae734b9d
Create Date: 2026-02-18 19:46:47.643932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2aec42bc51'
down_revision: Union[str, Sequence[str], None] = '835dae734b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('name', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('is_group', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('avatar_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_path')
    op.drop_column('chats', 'is_group')
    op.drop_column('chats', 'name')
    # ### end Alembic commands ###
